// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CounterReducer$ReactTemplate = require("./CounterReducer.bs.js");

var component = ReasonReact.reducerComponent("Counter");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var value = Pervasives.string_of_int(self[/* state */2][/* counter */0]);
      return React.createElement("div", undefined, React.createElement("h1", undefined, value), React.createElement("br", undefined), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(self[/* send */4], /* Increment */0);
                        })
                    }, "Increment"), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(self[/* send */4], /* Decrement */1);
                        })
                    }, "Decrement"));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* counter */0];
    });
  newrecord[/* reducer */12] = CounterReducer$ReactTemplate.counterReducer;
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
